export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST"
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS"
export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE"

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE"

export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS"
export const CLEAR_CART_FAILURE = "CLEAR_CART_FAILURE"

export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";